### PR TITLE
Update Set-PnPTenant.md

### PR DESCRIPTION
**Pull request by KoenZomers**
Correction to two attributes who were incorrectly shown

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by tseward** [comment]
Is this coming in a future release of `PnP.PowerShell`? I do not see it even on the current prerelease.

**Comment by KoenZomers** [comment]
@tseward Its in the current prerelease for a while already. Just would like the documentation on docs.microsoft.com to be updated as it reflects the wrong parameter name. Tomorrow (Friday) evening European time we will release version 1.9.0 of PnP PowerShell which will contain this as well.

Updated documentation is available here: https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/pull/110#issuecomment-999026851

PR through which this has been added is here:
https://github.com/pnp/powershell/pull/1430

Implementation here:
https://github.com/pnp/powershell/blob/329218b275b0b7e0570da06dee649ca8fe34dc02/src/Commands/Admin/SetTenant.cs#L226

**Comment by tseward** [comment]
Huh weird, I couldn't get it to show that parameter on macOS. That's OK, though. Thanks!

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@get-itips Please comment. Thanks

**Comment by get-itips** [comment]
> @get-itips Please comment. Thanks

As @KoenZomers is from the PnP community I think this is ok to merge.

**Review by get-itips — APPROVED** [review]

**Comment by tiburd** [comment]
close > reopen

**Comment by traya1** [comment]
closing/re-opening PR

**Pull request merged**
