### PR TITLE
Add AllowMediaTranscription Value

### PR DESCRIPTION
**Pull request by mskaai**
Adding guidance for AllowMediaTranscription boolean that controls transcript policy for admins to manage transcription generation for all videos in ODSP.  This will control the initial on demand feature allowing owners to request a transcript on demand as well as the longer term automatic feature which will transcribe more videos automatically in the background.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Comment by get-itips** [comment]
@mskaai are you a Microsoft Employee?

Here is a site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=mskaai

And if you have a Microsoft alias you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

**Review by tseward — APPROVED** [review]

**Comment by get-itips** [comment]
Is this going live in the next module version?
Checked with _16.0.21909.12000_ and it is not still there.

**Comment by yogkumgit** [comment]
@mskaai Please update. Thanks

**Comment by mskaai** [comment]
> @mskaai are you a Microsoft Employee?
> 
> Here is a site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=mskaai
> 
> And if you have a Microsoft alias you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

I am a Microsoft Employee! Let me follow those steps to make sure I have the blue "Microsoft submitter" label

**Comment by KoenZomers** [comment]
@mskaai Is the AllowMediaTranscription coming in a future update of the SPO Management Shell? In the currently latest available public version it does not seem to exist yet, nor does it in CSOM.

**Comment by mskaai** [comment]
> Is this going live in the next module version? Checked with _16.0.21909.12000_ and it is not still there.

Hi! Just checking back on this, it is going live in version 16.0.21909.12000

**Comment by mskaai** [comment]
> @mskaai Is the AllowMediaTranscription coming in a future update of the SPO Management Shell? In the currently latest available public version it does not seem to exist yet, nor does it in CSOM.

Hi, it should be published in version 16.0.21909.12000

**Pull request merged**
