### PR TITLE
Update sharepoint-pnp-cmdlets.md

### PR DESCRIPTION
**Pull request by VesaJuvonen**
Fixing wrong link and updating the intro text for PnP PowerShell

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@get-itips

**Review by get-itips — APPROVED** [review]

**Comment by get-itips** [comment]
@yogkumgit Vesa is part of the PnP community, this is ok to review/merge

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
