### PR TITLE
Remove SPO admin from cmdlets requirements.

### PR DESCRIPTION
**Pull request by dibetanz**

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Review by get-itips — APPROVED** [review]
Verified that you can't successfully use this cmdlet if you are a SPO Admin only. Thank you

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
