### PR TITLE
Update Set-SPOBuiltInSiteTemplateSettings.md

### PR DESCRIPTION
**Pull request by dewcatpaint1**
Submitted via Learn Editor.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by dariomws** [comment]
Accounts and contracts templates are not available in my demo tenant, maybe they will be available soon...

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by tiburd** [comment]
@dewcatpaint1 
Hi Cathy,
When you are finished with this PR, please select the **Ready for review** button above. 

image


We do not merge Draft pull requests.
Thank you!

**Comment by yogkumgit** [comment]
@dewcatpaint1 Gentle reminder. Thanks

**Comment by yogkumgit** [comment]
@dewcatpaint1 We proceed to close this PR. Thanks

**Pull request closed without merging**
