### PR TITLE
Adding MD

### PR DESCRIPTION
**Pull request by salarson**

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@get-itips @tseward

**Review by get-itips — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by tiburd** [comment]
@salarson 
Hi Sam,

Per [PubOps criteria](https://review.learn.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=main), when a file is renamed, an entry should be added to the redirect file:
image

Here's a link to instructions:
[Retire and redirect an article on learn.microsoft.com (DMC)](https://review.learn.microsoft.com/en-us/office-authoring-guide/retiring-redirecting-content?branch=main)

After you add the redirect, please @ mention me to review and merge this PR.

Thanks!

**Comment by yogkumgit** [comment]
@salarson Gentle reminder.

**Comment by yogkumgit** [comment]
@tiburd

**Pull request merged**
