### PR TITLE
Update Set-SPOTenantSyncClientRestriction.md

### PR DESCRIPTION
**Pull request by guzi99**
Remove the command GrooveBlockOption, as it is being depreciated.

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Review by get-itips — COMMENTED** [review]
Is this going to be removed from the module soon? the parameter is still there in 16.0.21909.12000 version
Thank you

**Review by dariomws — APPROVED** [review]

**Comment by guzi99** [comment]
> Is this going to be removed from the module soon? the parameter is still there in 16.0.21909.12000 version Thank you

Yes. Right now cmd is no op, as the related product is already deprecated.

**Comment by guzi99** [comment]
Sorry, clicked the wrong button and did not mean to close it. Please review and approve if you have no question.

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
