### PR TITLE
Module update

### PR DESCRIPTION
**Pull request by traya1**
Attempting to update module display value based on guidance from a SME.

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Comment by yogkumgit** [comment]
@dariomws @tseward @get-itips

**Review by dariomws — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by yogkumgit** [comment]
@get-itips

**Comment by yogkumgit** [comment]
@get-itips Gentle reminder

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by tiburd** [comment]
@traya1 
I'll leave this one for you. :)

**Pull request merged**
