### PR TITLE
Update BlockUserInfoVisibility doc

### PR DESCRIPTION
**Pull request by yimingMSFT**

### CODE REVIEW

**Comment by samkabue** [comment]
@yimingMSFT is there a corresponding change in backend cmdlet code?

**Comment by yimingMSFT** [comment]
> @yimingMSFT is there a corresponding change in backend cmdlet code?

Correct. This is backed by a backend change.

**Review by samkabue — APPROVED** [review]
:shipit:

**Comment by yimingMSFT** [comment]
@Stacyrch140 I see you merged other PRs. May I ask the process to merge this PR? Seems I do not have permission to merge it.

**Pull request merged**
