### PR TITLE
Branding change

### PR DESCRIPTION
**Pull request by get-itips**
Closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/issues/143

### CODE REVIEW

**Comment by traya1** [comment]
Hi @get-itips Andres,

You are correct, removing the ms.service attribute/value pair should resolve the warning. 

The ms.prod attribute is declared in the [docfx.json](https://github.com/get-itips/OfficeDocs-SharePoint-PowerShell/blob/patch-9/sharepoint/docfx.json#L44) file which means the value defined will apply to all topics within the sharepoint folder.

Let me know if this helps.

**Comment by get-itips** [comment]
@traya1 thank you

**Comment by yogkumgit** [comment]
@dariomws @tseward

**Review by dariomws — APPROVED** [review]
What I'm not sure is if we should change it to "Microsoft 365" or to "Microsoft 365 or Office 365".

I saw several articles with "Microsoft 365 or Office 365".

**Comment by tseward** [comment]
@dariomws the official rebranding happened awhile back from O365 -> M365.

**Review by tseward — APPROVED** [review]

**Comment by dariomws** [comment]
Thanks @tseward, I'm aware of that. But Office 365 is a term that you can still find in the documentation and you have Office 365 Ex licenses and Microsoft 365 Ex licenses.
For example:
https://docs.microsoft.com/exchange/mail-flow-best-practices/manage-mailboxes-using-microsoft-365-or-office-365
https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options
https://docs.microsoft.com/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
