### PR TITLE
add example

### PR DESCRIPTION
**Pull request by get-itips**
closes https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/issues/369

@tseward @dariomws please have a look

### CODE REVIEW

**Comment by dariomws** [comment]
@get-itips, did you test it?

I understand that a guest account with the Global Admin or SharePoint role cannot access the M365 or SP admin center.

**Comment by get-itips** [comment]
@dariomws I did, this is only to give site collection admin to a site. This does not give administrative access.

**Review by dariomws — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tseward

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by get-itips** [comment]
> why is this closed, to repeat in another github issue the same ? it does not have nothing with guest accounts, instead partner delegated admin, as describide in original github issue

Already asked about this on an internal thread and I expect it will take time to get an answer.

**Pull request merged**
