### PR TITLE
revert tws cmdlet documentation

### PR DESCRIPTION
**Pull request by praporwal-microsoft**
[PubOps PR review](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/pull/604#issuecomment-2027518684)

Reverting TWS cmdlets documentation.

### CODE REVIEW

**Review by samkabue — APPROVED** [review]
:shipit:

**Review by samkabue — APPROVED** [review]

**Comment by garycentric** [comment]
@samkabue  Are you able to add the _Sign off_ label?

**Comment by pamgreen-msft** [comment]
Signing off per Ask and Admin chat with @praporwal-microsoft and @garycentric. Thanks folks!

**Comment by Stacyrch140** [comment]
Hi @praporwal-microsoft  - 

**Following are blocking issues that need to be resolved before we can merge:**

sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTenantRestrictedSearchAllowedList.md
sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRestrictedSearchAllowedList.md
sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRestrictedSearchMode.md
sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantRestrictedSearchAllowedList.md
sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRestrictedSearchMode.md
- Update the corresponding TOC with these deletions, and include the TOC in this PR.  

***

**Reference**

[Criteria used for pull request reviews](https://review.docs.microsoft.com/en-us/office-authoring-guide/pr-criteria?branch=main)

**Blocking**
- When an article is deleted or a file is renamed, the PR includes a [redirect for the article in the .openpublishing.redirection.json file](https://review.learn.microsoft.com/en-us/office-authoring-guide/retiring-redirecting-content) for the repo. It also includes a TOC update to remove the file or change the name.

***

After you resolve the blocking issues, remove the **Back to submitter** label and add the **Sign off** label again. 

If you need help resolving issues in this PR, post your question in the [Ask an Admin Teams Channel](https://teams.microsoft.com/l/channel/19%3aea9a561f603c4fbb9cf3931a6849eae4%40thread.skype/Ask%2520an%2520Admin?groupId=7079ffbf-1420-4ee2-9ddc-a2c351337320&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47).


Thanks, 
Stacy

**Comment by garycentric** [comment]
@Stacyrch140, @praporwal-microsoft 
It's unusual, compared to almost all of our repositories, but the PowerShell repos don't have entries for the articles of the reference pages (and the existing TOC files in the PowerShell repos might not be used at all—I'm not sure at the moment).

**Comment by samkabue** [comment]
> @samkabue Are you able to add the _Sign off_ label?

@garycentric unfortunately I don't have the permissions to do that.

**Pull request merged**
