### PR TITLE
Update Set-SPOTenant.md

### PR DESCRIPTION
**Pull request by liamfernandez**
For some reason, one of the parameters for Set-SPOTenant shows up as "undefined".
In this change, I add the type for -ReSyncTenantPrivacyProfile param to be set to SwitchParameter so it no longer shows "undefined"

### CODE REVIEW

**Comment by liamfernandez** [comment]
@kaarins

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Comment by yogkumgit** [comment]
@get-itips @tseward

**Review by get-itips — APPROVED** [review]

**Review by tseward — APPROVED** [review]

**Comment by liamfernandez** [comment]
Ready to merge? @tseward

**Comment by tseward** [comment]
@liamfernandez yep I already did my approval. I believe @tiburd is responsible for performing the merge.

**Pull request merged**
