### PR TITLE
Update sharepoint-online.md to add links to SPOListDesign cmdlets

### PR DESCRIPTION
**Pull request by alinsirbu**
This PR updates the SharePoint Online PowerShell cmdlet TOC to add references to these new cmdlets:
[Create Add-SPOListDesign.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/pull/462)
[Create Get-SPOListDesign.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/pull/463)
[Create Remove-SPOListDesign.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint-PowerShell/pull/464)

### CODE REVIEW

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Comment by alinsirbu** [comment]
@tiburd the 3 open PRs mentioned in my top comment need to merge first

**Comment by tiburd** [comment]
@alinsirbu 
Thank you for letting me know. Please @ mention me again in this PR when it is ready to be merged.

**Comment by alinsirbu** [comment]
@tiburd This PR is now ready to be merged. Thank you!

**Comment by yogkumgit** [comment]
@tiburd

**Pull request merged**
