### PR TITLE
Update Revoke-SPOTenantServicePrincipalPermission.md

### PR DESCRIPTION
**Pull request by PowershellScripts**
Added missing parameter

### CODE REVIEW

**Comment by yogkumgit** [comment]
@JohanFreelancer9

**Review by tseward — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Review by dariomws — APPROVED** [review]

**Review by get-itips — COMMENTED** [review]
please add it to the parameter syntax, for example like here https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/revoke-spousersession?view=sharepoint-ps

**Comment by yogkumgit** [comment]
@PowershellScripts

**Comment by yogkumgit** [comment]
@PowershellScripts Gentle reminder. Thanks

**Review by get-itips — APPROVED** [review]

**Comment by yogkumgit** [comment]
@tiburd Please merge this PR. Thanks

**Pull request merged**
