### PR TITLE
Added notice of removal of Export-SPOQueryLogs

### PR DESCRIPTION
**Pull request by karolikl**
Added notice of removal as Export-SPOQueryLogs will not be supported beginning February 2022. It is replaced by the Microsoft Search download search history feature in https://myaccount.microsoft.com/settingsandprivacy/privacy.

### CODE REVIEW

**Review by tseward — APPROVED** [review]

**Review by JohanFreelancer9 — APPROVED** [review]

**Comment by yogkumgit** [comment]
@dariomws  @get-itips

**Review by get-itips — APPROVED** [review]
I am ok but the build is currently throwing errors, maybe a close and reopen by @tiburd will fix it.

**Comment by yogkumgit** [comment]
@dariomws

**Review by dariomws — APPROVED** [review]

**Comment by tiburd** [comment]
close > reopen

**Comment by tiburd** [comment]
@traya1 
Hi, Thomas,
Can you please help?
Thanks!

**Comment by traya1** [comment]
Hi @tiburd,

Given that the topics with warnings were not modified by the contributor, I created a replacement PR with the proposed change. 

It looks like the original change was approved for merging and I will merge the replacement once all checks are cleared.

Lastly, I believe that a known bug affected this PR so I will apply the "Do not merge" and leave only myself as the assignee for troubleshooting at a later date.

Let me know if ya'll have any questions or concerns.

Thanks!

**Comment by yogkumgit** [comment]
@traya1 please take next step and resolve this PR. thanks

**Comment by yogkumgit** [comment]
@traya1

**Pull request merged**
